services:
  - type: web
    name: recipe-finder-api
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SPOONACULAR_KEY
        sync: false